# Generated by Django 4.1.3 on 2023-01-10 00:02

import datetime
from django.db import migrations, models
import django_quill.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', django_quill.fields.QuillField()),
                ('option_one', models.CharField(max_length=80)),
                ('option_two', models.CharField(max_length=80)),
                ('option_three', models.CharField(max_length=80)),
                ('option_four', models.CharField(max_length=80)),
                ('option_one_count', models.IntegerField(default=0)),
                ('option_two_count', models.IntegerField(default=0)),
                ('option_three_count', models.IntegerField(default=0)),
                ('option_four_count', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=80)),
                ('profile', models.CharField(blank=True, max_length=222)),
                ('email', models.CharField(max_length=80)),
                ('total', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expiration_date', models.DateTimeField(default=datetime.datetime(2023, 1, 10, 0, 2, 35, 117711))),
            ],
        ),
        migrations.CreateModel(
            name='UserRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_pic', models.ImageField(blank=True, upload_to='User_Portal/profiles')),
                ('first_name', models.CharField(max_length=80)),
                ('last_name', models.CharField(max_length=80)),
                ('mobile_number', models.CharField(max_length=122)),
                ('email', models.CharField(max_length=122)),
                ('gender', models.CharField(max_length=122)),
            ],
            options={
                'db_table': 'Poll_user_registration',
            },
        ),
    ]
