# Generated by Django 4.1.3 on 2023-01-10 12:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Poll', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 11, 12, 11, 21, 846352, tzinfo=datetime.timezone.utc)),
        ),
    ]
